name: deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag main-app:$(date +%s)

      - name: Deploy stack to Portainer
        uses: kgierke/portainer-stack-deployment@v1
        with:
          portainer-url: ${{ secrets.PORTAINER_HOST }}
          portainer-username: ${{ secrets.PORTAINER_USERNAME }}
          portainer-password: ${{ secrets.PORTAINER_PASSWORD }}
          portainer-endpoint: 2
          name: fckffln-main
          file: stack-definition.yml
          variables: '{"image": "main-app:$(date +%s)"}'